config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "albums#index"
  get '/album/tag/:name', to: "albums#tag"
  resources :users, only: [:show, :edit, :update]
  resources :albums do
    resources :comments, only: :create
  end
end

app/models/album.rb
class Album < ApplicationRecord
  
  #アソシエーション
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image
  has_many :album_tag_relations, dependent: :destroy
  has_many :tags, through: :album_tag_relations

  #バリデーション
  with_options presence: true do
    validates :description
    validates :image
    validates :user_id
  end
  
  after_create do
    album = Album.find_by(id: self.id)
    tags  = self.description.scan(/[#][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    album.tags = []
    tags.uniq.map do |tag|
      #ハッシュタグは先頭の'#'を外した上で保存
      tag = Tag.find_or_create_by(tag_name: tag.downcase.delete('#'))
      album.tags << tag
    end
  end

  before_update do 
    album = Album.find_by(id: self.id)
    album.tags.clear
    tags = self.description.scan(/[#][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    tags.uniq.map do |tag|
      tag = Tag.find_or_create_by(tag_name: tag.downcase.delete('#'))
      album.tags << tag
    end
  end

  #def exif_data
    #if image.attached? && image.blob.variable?
      #exif_data = Exiftool.new(image.blob.service.send(:path_for, image.blob.key)).to_hash
      #return exif_data
    #end
  #end

  #ローカル環境のみ動作するexiftool
  #<p class="information__title">情報</p>
  #<li><strong>撮影日:</strong> <%= l(DateTime.strptime(@album.exif_data[:date_time_original], '%Y:%m:%d %H:%M:%S'), format: :custom) %></li>
  #<li><strong>カメラ情報:</strong> <%= @album.exif_data[:model] %></li>
  #<li><strong>絞り値:</strong> <%= @album.exif_data[:aperture] %></li>
  #<li><strong>シャッタースピード:</strong> <%= @album.exif_data[:shutter_speed] %></li>
  #<li><strong>ISO感度:</strong> <%= @album.exif_data[:iso] %></li>
  
end

app/models/album_tag_relation.rb
class AlbumTagRelation < ApplicationRecord
  #アソシエーション
  belongs_to :album
  belongs_to :tag
  
  #バリデーション
  with_options presence: true do
    validates :album_id
    validates :tag_id
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  #アソシエーション
  belongs_to :user
  belongs_to :album

  #バリデーション
  with_options presence: true do
    validates :content
    validates :album
    validates :user
  end
  
end

app/models/tag.rb
class Tag < ApplicationRecord
 
  #アソシエーション
  has_many :album_tag_relations
  has_many :albums, through: :album_tag_relations
  
  #バリデーション
  validates :tag_name, presence: true, length: {maximum:99}
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  #テーブルとのアソシエーション
  has_many :albums
  has_many :comments

  #バリデーション
  with_options presence: true do
    validates :nickname
    
    PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates_format_of :password, with: PASSWORD_REGEX
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  
  def index
    @albums = Album.all
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @album.comments.includes(:user)
  end

  def tag
    @user = current_user
    @tag = Tag.find_by(tag_name: params[:name])
    @albums = @tag.albums
  end

  def edit
    unless current_user.id == @album.user_id
      redirect_to action: :index
    end
  end

  def update
    if @album.update(album_params)
      redirect_to album_path
    else
      render :edit
    end
  end

  def destroy
    @album.destroy
    redirect_to root_path
  end

  private

  def set_album
    @album = Album.find(params[:id])
  end

  def album_params
    params.require(:album).permit(:description, :tag_name, :image).merge(user_id: current_user.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to album_path(@comment.album)
    else
      @album = @comment.album
      @comments = @album.comments
      render "albums/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, album_id: params[:album_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  
  def show
    @albums = @user.albums
  end

  def edit
    unless current_user == @user
      redirect_to root_path
    end
  end

  def update
    if @user.update(user_params)
      bypass_sign_in(@user)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
  def render_with_tags(description)
    description.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/album/tag/#{word.delete("#")}"}.html_safe
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/album/_form.html.erb
<%= form_with model: @prototype, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "プロトタイプの名称" %><br />
    <%= f.text_field :title, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/album/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: "form", locals: {form: @form} %>
    </div>
  </div>
</div>

app/views/album/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、<%= link_to "#{current_user.name}さん", "/users/#{current_user.id}", class: :greeting__link %>
      </div>
    <% end %>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
      <%= render partial: "prototype", collection: @prototypes %>
    </div>
  </div>
</main>

app/views/album/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.title %>
      </p>
      <%= link_to @prototype.user.name , user_path(@prototype.user.id), class: :prototype__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @prototype.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_prototype_path(@prototype.id), class: :prototype__btn, method: :get %>
          <%= link_to "削除する", prototype_path(@prototype.id), class: :prototype__btn, method: :delete %>
        </div>
      <% end  %>
      <div class="prototype__image">
        <%= image_tag @prototype.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @prototype.catch_copy %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.concept %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
        <% if user_signed_in? %>
          <%= form_with(model: [@prototype, @comment], local: true) do |f| %>
            <div class="field">
              <%= f.label :content, "コメント" %><br />
              <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.content %>
              <%= link_to comment.user.name , "/users/#{comment.user_id}", class: :comment_user %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/albums/_album.html.erb
<div class=“card”>
  <div class="card__img">
    <%= link_to image_tag(album.image), album_path(album.id) %>
  </div>
</div>

app/views/albums/_form.html.erb
<%= form_with model: @album, id: 'new_post', local: true do |f|%>
  
  <%= render 'layouts/error_messages', model: f.object %>

  <div class="field">
    <%= f.label :description, "説明" %><br />
    <%= f.text_area :description, class:"form__text", id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <div class="previews" id="previews"></div>
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "投稿する", class: :form__btn %>
  </div>

<% end %>

app/views/albums/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">写真編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: "form", locals: {form: @form} %>
    </div>
  </div>
</div>

app/views/albums/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、<%= link_to "#{current_user.nickname}さん", "/users/#{current_user.id}", class: :greeting__link %>
      </div>
    <% end %>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿一覧を表示する %>
      <%= render partial: "album", collection: @albums %>
    </div>
  </div>
</main>

app/views/albums/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">写真投稿</h2>
        <%= render partial: "form", locals: {form: @form} %>
    </div>
  </div>
</div>

app/views/albums/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <div class="prototype__user">
        投稿者: <%= link_to @album.user.nickname, user_path(@album.user.id) %>
      </div>
      <%# 投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @album.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_album_path(@album.id), class: :prototype__btn, method: :get %>
          <%= link_to "削除する", album_path(@album.id), class: :prototype__btn, method: :delete %>
        </div>
      <% end  %>
      <div class="prototype__image">
        <%= image_tag @album.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">説明</p>
          <p class="detail__message">
            <%= render_with_tags(safe_join(@album.description.split("\n"),tag(:br))) %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
        <% if user_signed_in? %>
          <%= form_with(model: [@album, @comment], local: true) do |f| %>
            <%= render 'layouts/error_messages', model: f.object %>
            <div class="field">
              <%= f.label :content, "コメント" %><br />
              <%= f.text_field :content, id:"comment_content", class:"input-box" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.content %>
              <%= link_to comment.user.nickname , "/users/#{comment.user_id}", class: :comment_user %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/albums/tag.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、<%= link_to "#{current_user.nickname}さん", "/users/#{current_user.id}", class: :greeting__link %>
      </div>
    <% end %>
    <%# // ログインしているときは上記を表示する %>
    #<%= @tag.tag_name %> 
    <div class="card__wrapper">
      <%# 投稿一覧を表示する %>
      <%= render partial: "album", collection: @albums %>
    </div>
  </div>
</main>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SharedPic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logoo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "ユーザー編集", edit_user_path(current_user), class: :nav__edit__user %>
              <%= link_to "投稿する", new_album_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © S H A R E D P I C All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">ユーザー編集機能</h2>
      <%= form_with model: @user, local: true do |f| %>

        <%= render 'layouts/error_messages', model: f.object %>

        <div class="field">
          <%= f.label :email, "メールアドレス" %><br />
          <%= f.email_field :email, id:"user_email", class:"input-box", autofocus: true, autocomplete: "email" %>
        </div>

        <div class="field">
          <%= f.label :password, "パスワード（6文字以上）" %><br />
          <%= f.password_field :password, id:"user_password", class:"input-box", autocomplete: "new-password" %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation, "パスワード再入力" %><br />
          <%= f.password_field :password_confirmation, id:"user_password_confirmation", class:"input-box", autocomplete: "new-password" %>
        </div>

        <div class="field">
          <%= f.label :current_password %> <br />
          <%= f.password_field :current_password, autocomplete: "current-password", id:"current-password", class:"input-box" %>
        </div>

        <div class="actions">
          <%= link_to "Back", root_path, class: :form__btn %> <%= f.submit "Update", class: :form__btn %>  
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= @user.nickname %>さんの投稿一覧
      </h2>
      <div class="user__card">
        <%= render partial: "albums/album", collection: @albums %>
      </div>
    </div>
  </div>
</div>